### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by zobzn** [FriendsOfSymfony1/symfony1#147]
What do you think about PSR-1/2 and `friendsofphp/php-cs-fixer` ?
When possible (spaces, braces, etc... without breaking changes such as introducing namespacing)

**Comment by j0k3r** [comment]
Why not, it'll generate a huge PR with lot of changes.
And as far as I remember symfony1 used a _custom_ CS which compatible with a PSR.

**Comment by mkopinsky** [comment]
I think *true* PSR-compatibility is impossible, since PSR-2 requires PSR-1 which requires PSR-0 or PSR-4, both of which are incompatible with symfony's classloading patterns.

If there's a way to make a `phpcs` config file that says "enforce (and/or autofix) all of PSR-1/2 except for the namespacing/classloading stuff", that would be valuable not just for symfony1 itself but for any symfony1 projects.
