### ISSUE TITLE
PHP 7.3 Support

### ISSUE THREAD

**Issue by charmoller** [FriendsOfSymfony1/symfony1#243]
Does this fork of symfony1 support PHP 7.3? Now that PHP 7.2 is out of support we are planning to upgrade our Symfony 1.4 application to PHP 7.3 and are investigating options.

**Comment by ingcarlosperez** [comment]
I use this fork with PHP7.4 without any problem.

**Comment by DavidGoodwin** [comment]
ditto, works fine with PHP 7.4 as well.

**Comment by mentalstring** [comment]
Semi-tangent: from those running it with PHP 7.4, are you using propel1 (sfPropelORMPlugin) with it?

**Comment by DavidGoodwin** [comment]
> Semi-tangent: for those running it with PHP 7.4, are you using propel1 (sfPropelORMPlugin) with it? Is that working well with PHP 7.4?

We are using Doctrine, sorry. There are a few git repos around for Propel 1.7 with PHP 7.4 support ... but perhaps that's the wrong version of Propel for symfony?

**Comment by mentalstring** [comment]
> but perhaps that's the wrong version of Propel for symfony?

I'm afraid that that is the only one with existing symfony1 integration (admin generator, crud, forms, etc) through sfPropelORMPlugin.

**Comment by e1himself** [comment]
> Semi-tangent: for those running it with PHP 7.4, are you using propel1 (sfPropelORMPlugin) with it? Is that working well with PHP 7.4?

We at @prezly are maintaining our own forks of symfony1, propel1 and propel-orm-plugin to fix bugs and compatibility issues. AFAIK propel-orm-plugin works well with PHP up to 7.4. However, we had to apply a bunch of fixes to Propel1 in order to make it work on PHP 7.4 without throwing warnings:

- https://github.com/rock-symphony/propel-orm/pull/3
- https://github.com/rock-symphony/propel-orm/pull/5
- https://github.com/rock-symphony/propel-orm/pull/7
