### ISSUE TITLE
sfPropelORMPlugin doesnt fit in after update symfony1

### ISSUE THREAD

**Issue by devmuc** [FriendsOfSymfony1/symfony1#288]
After updating symfony1 (v1.5.11 => v1.5.15) there is a problem to embed propel/sf-propel-o-r-m-plugin

`# ./symfony cc
PHP Fatal error:  Cannot declare class XMLElement, because the name is already in use in /var/symfony/vendor/propel/propel1/generator/lib/model/XMLElement.php on line 20`

only with >= PHP8.0

**Comment by connorhu** [comment]
If you create a repo for testing, I'll try to figure out what's going on here.

**Comment by mentalstring** [comment]
Not sure if relevant, but propel1 (and not necessarily propel/sf-propel-o-r-m-plugin) has limited PHP 8 support. There's some good work for that at https://github.com/tworzenieweb/Propel/tree/feature/php8.0 and I have done some additional changes at https://github.com/mentalstring/Propel/tree/feature/php8.1 for PHP 8.1 and I've been using that with PHP 8.2 with no issues — YMMV.

Having said that, my guess is that this issue isn't specific to symfony1 and maybe should be created in https://github.com/propelorm/sfPropelORMPlugin or https://github.com/propelorm/Propel.

@devmuc Are you still hitting this? Did you try manually clearing the cache folder by removing the files (instead of `symfony cc`)?

**Comment by connorhu** [comment]
@mentalstring I have never used propel. Do you actively use it? I've looked at your modifications and I see little BC like, but it doesn't seem too bad. Should we bring it under the fos1 organization as well?

**Comment by mentalstring** [comment]
While my changes are enough for my needs to use it with PHP 8.2, I don't think it's ready for general availability due to the BC changes (mostly due to `strftime()` being deprecated, which I can live without).

> Should we bring it under the fos1 organization as well?

Would need to see more people interested in this and helping cover the gaps I missed/don't use. That said, `strftime()` parity seems [hard](https://github.com/alphp/strftime/issues/8) so probably it will never be perfect.

**Comment by connorhu** [comment]
@mentalstring I didn't know there were such problems with propel. I looked at some of the more active forks, but I didn't really see anyone doing anything about this problem. In general, I think this could be solved by making a tool to migrate data that relies on the strftime function.

**Comment by connorhu** [comment]
```
vendor/bin/phpunit       
PHP Fatal error:  Cannot declare class XMLElement, because the name is already in use in /Users/connor/Work/opensource/propel/generator/lib/model/XMLElement.php on line 20
```
I was able to reproduce it. php 8.3 is indeed problematic with the basic repo.
